### ISSUE TITLE
How to interprete results?

### ISSUE THREAD

**Issue by BinkertR** [camilleg/clockkit#20]
Hello,
I am pretty new to time synchronization.
I have installed and successfully ran the clockkit sync.

However, I don't understand how to interprete the results.
As I understand, the software should give me two timestamps, one on the host and one on the client that correspond to each other.
How should I then understand the command line ouputs?

I would really appreciate your help!

It gives me the follwing results on the host.
<time 1671706538 646372> offsetMax	958	---
<time 1671706538 841717> 192.168.1.128	200	992
<time 1671706539  51321> 192.168.1.128	41	734
<time 1671706539 245279> 192.168.1.128	37	834
<time 1671706539 245279> offsetMax	454	---
<time 1671706539 455172> 192.168.1.128	27	841
<time 1671706539 649876> 192.168.1.128	226	1256
<time 1671706539 855896> 192.168.1.128	68	823
<time 1671706539 855896> offsetMax	479	---
<time 1671706540  52855> 192.168.1.128	119	1002
<time 1671706540 262814> 192.168.1.128	62	890
<time 1671706540 459118> 192.168.1.128	44	728
<time 1671706540 459118> offsetMax	408	---
<time 1671706540 654233> 192.168.1.128	2	661
<time 1671706540 861885> 192.168.1.128	194	1115
<time 1671706541  63815> 192.168.1.128	38	911
<time 1671706541  63815> offsetMax	493	---
<time 1671706541 258405> 192.168.1.128	-53	1039
<time 1671706541 457905> 192.168.1.128	23	916
<time 1671706541 665429> 192.168.1.128	205	1245
<time 1671706541 665429> offsetMax	827	---
<time 1671706541 868078> 192.168.1.128	61	969
<time 1671706542  67013> 192.168.1.128	11	888
<time 1671706542 271299> 192.168.1.128	11	954

**Comment by camilleg** [comment]
The output of ./ckserver is _only informational_, from ClockServerMain.cpp's `server.setLogging(true);`.  What really matters are the timestamps that clients (./ckphaselock, python/ckphaselock.py, etc.) get by calling `ckTimeAsString` or `ckTimeAsValue`.

To get synced timestamps on two (or more) hosts, run a client on each host, and run the server somewhere (possibly on a host that's already running a client).  Get the timestamps from the clients, not directly from the host.

Anyhow, ./ckserver's output is:
- the time "now", in seconds + microseconds since the Unix epoch;
- either a client's IP address followed by the client's clock's offset in microseconds,
  or "offsetMax" followed by the largest offset of all currently connected clients (updated every few seconds).

(I've incorporated this comment into ClockServer.cpp, where it prints these messages.)
